#ifndef PREXY_01_ENUM_H_
#define PREXY_01_ENUM_H_

/* Generated by prexy from: 01_enum.c */

// prexy enum error {
//     // Ok
//     OK = 0,
//     // bad
//     ERR,
// };
#define error_x_variants(X)                                                    \
    X(OK)                                                                      \
    X(ERR)

#define error_x_count 2

#endif
