#ifndef PREXY_CLIENT_05_ATTRS_H_
#define PREXY_CLIENT_05_ATTRS_H_

/* Generated by prexy from: 05_attrs.c */

#include "prexy.h"

// prexy struct cstr
// {
//     px_attr(strattr, .is_cstr = true);
//     char const *buf;
//
//     px_attr(strattr, 0);
//     char const *ptr;
//
//     size_t len;
// };
#define cstr_x_fields(F)                                                       \
    F(simple, char const *, buf)                                               \
    F(simple, char const *, ptr)                                               \
    F(simple, size_t, len)

#define cstr_x_fields_strattr(F)                                               \
    F(strattr, char const *, buf, .is_cstr = true)                             \
    F(strattr, char const *, ptr, 0)                                           \
    F(simple, size_t, len)

// prexy struct messages
// {
//     struct cstr buf[5];
// };
#define messages_x_fields(F) F(struct_array, cstr, buf, 5)

#endif
