#ifndef PREXY_CLIENT_05_ATTRS_H_
#define PREXY_CLIENT_05_ATTRS_H_

/* Generated by prexy from: 05_attrs.c */

#include "prexy.h"

// prexy struct cstr
// {
//     px_attr(strattr, .is_cstr = true);
//     char const *buf;
//
//     size_t len;
// };
#define cstr_x_fields(F)                                                       \
    F(simple, char const *, buf)                                               \
    F(simple, size_t, len)

#define cstr_x_fields_strattr(F)                                               \
    F(strattr, char const *, buf, .is_cstr = true)                             \
    F(simple, size_t, len)

#endif
