#ifndef PREXY_TEMPLATE_H_
#define PREXY_TEMPLATE_H_

// Field implementations

#define PREXY_FN_simple(type, varname)                                         \
    {                                                                          \
        (x)->varname;                                                          \
    }

#define PREXY_FN_simple_array(type, varname, len)                              \
    {                                                                          \
        for (int i = 0; i < len; ++i)                                          \
        {                                                                      \
            (x)->varname[i];                                                   \
        }                                                                      \
    }

#define PREXY_FN_struct(type, varname)                                         \
    {                                                                          \
        (x)->varname;                                                          \
    }

#define PREXY_FN_struct_array(type, varname, len)                              \
    {                                                                          \
        for (int i = 0; i < len; ++i)                                          \
        {                                                                      \
            (x)->varname[i];                                                   \
        }                                                                      \
    }

#define PREXY_FN_enum(type, varname)                                           \
    {                                                                          \
        (x)->varname;                                                          \
    }

#define PREXY_FN_enum_array(type, varname, len)                                \
    {                                                                          \
        for (int i = 0; i < len; ++i)                                          \
        {                                                                      \
            (x)->varname[i];                                                   \
        }                                                                      \
    }

// Field selector
#define PREXY_FN_FIELD_SELECT(fkind, ...) PREXY_FN_##fkind(__VA_ARGS__)

// Function prototype
#define prexy_fn_decl(name) void name##_fn(FILE *stream, struct name const *x)

// Implement with explicit XMacro
#define prexy_fn_impl_x(name, FIELDS_X)                                        \
    prexy_fn_decl(name) { FIELDS_X(PREXY_FN_FIELD_SELECT) }                    \
    static_assert(1, "")

// Prexy Pre-Processor supported macros

// Implement from implicit name##_x_fields XMacro generated by prexyp
#define prexy_fn_impl(name) prexy_fn_impl_x(name, name##_x_fields)

// Implement from implicit name##_x_fields_##attr XMacro generated by prexp
#define prexy_fn_impl_attr(name, attr)                                         \
    prexy_fn_impl_x(name, name##_x_fields_##attr);                             \
    static_assert(sizeof(*(struct attr *)0), "")

// Implement from implicit name##_x_fields_##tag XMacro generated by prexp
#define prexy_fn_impl_tag(name, tag) prexy_fn_impl_attr(name, tag)

#endif
