#ifndef PREXY_CLIENT_01_ENUM_H_
#define PREXY_CLIENT_01_ENUM_H_

/* Generated by prexy from: 01_enum.c */

#include "prexy.h"

// prexy enum foo {
//     bar,
//     baz = 10,
// };
#define foo_COUNT 2
#define foo_X(X)                                                               \
    X(bar)                                                                     \
    X(baz)

// prexy enum Bool {
//     // False
//     False,
//     // True
//     True,
//     // What is Truth?
//     FileNotFound
// };
#define Bool_COUNT 3
#define Bool_X(X)                                                              \
    X(False)                                                                   \
    X(True)                                                                    \
    X(FileNotFound)

#endif
