#ifndef PREXY_CLIENT_04_STRUCT_FPRINTF_H_
#define PREXY_CLIENT_04_STRUCT_FPRINTF_H_

/* Generated by prexy from: 04_struct_fprintf.c */

#include "prexy.h"

// prexy enum cheese_kind {
//     CHEDDAR,
//     SWISS,
//     BRIE,
// };
#define cheese_kind_COUNT 3
#define cheese_kind_X(X)                                                       \
    X(CHEDDAR)                                                                 \
    X(SWISS)                                                                   \
    X(BRIE)

// prexy struct cheese
// {
//     enum cheese_kind kind;
//     bool is_melty;
// };
#define cheese_X(F)                                                            \
    F(enum, cheese_kind, kind)                                                 \
    F(simple, bool, is_melty)

#define cheese_FIELDTYPE_kind enum cheese_kind
#define cheese_IS_MUT_PTR_kind 0
#define cheese_IS_CONST_PTR_kind 0
#define cheese_FIELDTYPE_is_melty bool
#define cheese_IS_MUT_PTR_is_melty 0
#define cheese_IS_CONST_PTR_is_melty 0

// prexy struct bagel
// {
//     char name[10];
//     double price;
//     struct cheese cheeses[3];
// };
#define bagel_X(F)                                                             \
    F(simple_array, char, name, 10)                                            \
    F(simple, double, price)                                                   \
    F(struct_array, cheese, cheeses, 3)

#define bagel_FIELDTYPE_name char *
#define bagel_IS_MUT_PTR_name 0
#define bagel_IS_CONST_PTR_name 0
#define bagel_FIELDTYPE_price double
#define bagel_IS_MUT_PTR_price 0
#define bagel_IS_CONST_PTR_price 0
#define bagel_FIELDTYPE_cheeses struct cheese *
#define bagel_IS_MUT_PTR_cheeses 0
#define bagel_IS_CONST_PTR_cheeses 0

#endif
