#ifndef PREXY_CLIENT_06_ATTR_H_
#define PREXY_CLIENT_06_ATTR_H_

/* Generated by prexy from: 06_attr.c */

#include "prexy.h"

// prexy struct cstr
// {
//     px_attr(strattr, .is_cstr = true);
//     char const *buf;
//
//     px_attr(fooattr, 0);
//     px_attr(strattr, 0);
//     char const *ptr;
//
//     size_t len;
// };
#define cstr_X(F)                                                              \
    F(simple, char const *, buf)                                               \
    F(simple, char const *, ptr)                                               \
    F(simple, size_t, len)

#define cstr_X_strattr(F)                                                      \
    F(strattr, char const *, buf, .is_cstr = true)                             \
    F(strattr, char const *, ptr, 0)                                           \
    F(simple, size_t, len)

#define cstr_X_fooattr(F)                                                      \
    F(simple, char const *, buf)                                               \
    F(fooattr, char const *, ptr, 0)                                           \
    F(simple, size_t, len)

#define cstr_FIELDTYPE_buf char const *
#define cstr_IS_MUT_PTR_buf 0
#define cstr_IS_CONST_PTR_buf 1
#define cstr_PTRTYPE_buf char
#define cstr_FIELDTYPE_ptr char const *
#define cstr_IS_MUT_PTR_ptr 0
#define cstr_IS_CONST_PTR_ptr 1
#define cstr_PTRTYPE_ptr char
#define cstr_FIELDTYPE_len size_t
#define cstr_IS_MUT_PTR_len 0
#define cstr_IS_CONST_PTR_len 0

// prexy struct messages
// {
//     struct cstr buf[6];
// };
#define messages_X(F) F(struct_array, cstr, buf, 6)

#define messages_FIELDTYPE_buf struct cstr *
#define messages_IS_MUT_PTR_buf 0
#define messages_IS_CONST_PTR_buf 0

#endif
