#ifndef PREXY_CLIENT_06_ATTR_H_
#define PREXY_CLIENT_06_ATTR_H_

/* Generated by prexy from: 06_attr.c */

#include "prexy.h"

// prexy struct cstr
// {
//     px_attr(strattr, .is_cstr = true);
//     char const *buf;
//
//     px_attr(fooattr, 0);
//     px_attr(strattr, 0);
//     char const *ptr;
//
//     size_t len;
// };
#define cstr_X(F)                                                              \
    F(simple, char const *, buf)                                               \
    F(simple, char const *, ptr)                                               \
    F(simple, size_t, len)

#define cstr_X_strattr(F)                                                      \
    F(strattr, char const *, buf, .is_cstr = true)                             \
    F(strattr, char const *, ptr, 0)                                           \
    F(simple, size_t, len)

#define cstr_X_fooattr(F)                                                      \
    F(simple, char const *, buf)                                               \
    F(fooattr, char const *, ptr, 0)                                           \
    F(simple, size_t, len)

// prexy struct messages
// {
//     struct cstr buf[6];
// };
#define messages_X(F) F(struct_array, cstr, buf, 6)

#endif
