#ifndef PREXY_CLIENT_07_TRAIT_H_
#define PREXY_CLIENT_07_TRAIT_H_

/* Generated by prexy from: 07_trait.h */

#include "prexy.h"

// prexy struct str
// {
//     char *ptr;
//     size_t len;
// };
#define str_X(F)                                                               \
    F(simple, char *, ptr)                                                     \
    F(simple, size_t, len)

#define str_FIELDTYPE_ptr char *
#define str_IS_MUT_PTR_ptr 1
#define str_IS_CONST_PTR_ptr 0
#define str_PTRTYPE_ptr char
#define str_FIELDTYPE_len size_t
#define str_IS_MUT_PTR_len 0
#define str_IS_CONST_PTR_len 0

// prexy struct strview
// {
//     char const *ptr;
//     size_t len;
// };
#define strview_X(F)                                                           \
    F(simple, char const *, ptr)                                               \
    F(simple, size_t, len)

#define strview_FIELDTYPE_ptr char const *
#define strview_IS_MUT_PTR_ptr 0
#define strview_IS_CONST_PTR_ptr 1
#define strview_PTRTYPE_ptr char
#define strview_FIELDTYPE_len size_t
#define strview_IS_MUT_PTR_len 0
#define strview_IS_CONST_PTR_len 0

#endif
