#ifndef PREXY_CLIENT_02_STRUCT_H_
#define PREXY_CLIENT_02_STRUCT_H_

/* Generated by prexy from: 02_struct.c */

#include "prexy.h"

// prexy struct simples
// {
//     // Comments
//     int i;
//     // things
//     char const *str;
// };
#define simples_x_fields(F)                                                    \
    F(simple, int, i)                                                          \
    F(simple, char const *, str)

// prexy struct arrays
// {
//     int arr[5];
//     char const *strings[80];
// };
#define arrays_x_fields(F)                                                     \
    F(simple_array, int, arr, 5)                                               \
    F(simple_array, char const *, strings, 80)

// prexy enum nums {
//     ONE,
//     TWO,
// };
#define nums_x_count 2
#define nums_x_variants(X)                                                     \
    X(ONE)                                                                     \
    X(TWO)

// prexy struct enums
// {
//     enum nums a_num;
//     enum nums nums[3];
// };
#define enums_x_fields(F)                                                      \
    F(enum, nums, a_num)                                                       \
    F(enum_array, nums, nums, 3)

// prexy struct nested
// {
//     struct simples head;
//     struct simples tail[11];
//     struct simples *simple_ref;
// };
#define nested_x_fields(F)                                                     \
    F(struct, simples, head)                                                   \
    F(struct_array, simples, tail, 11)                                         \
    F(simple, struct simples *, simple_ref)

#endif
