#ifndef PREXY_CLIENT_03_ENUM_TO_CSTR_H_
#define PREXY_CLIENT_03_ENUM_TO_CSTR_H_

/* Generated by prexy from: 03_enum_to_cstr.c */

#include "prexy.h"

// prexy enum tst3 {
//     FOO,
//     BAR,
//     BAZ,
// };
#define tst3_x_count 3
#define tst3_x_variants(X)                                                     \
    X(FOO)                                                                     \
    X(BAR)                                                                     \
    X(BAZ)

#endif
