#ifndef PREXY_CLIENT_05_TAG_H_
#define PREXY_CLIENT_05_TAG_H_

/* Generated by prexy from: 05_tag.c */

#include "prexy.h"

// prexy struct cstr
// {
//     px_tag(format_as_str);
//     char const *buf;
//
//     size_t len;
// };
#define cstr_x_fields(F)                                                       \
    F(simple, char const *, buf)                                               \
    F(simple, size_t, len)

#define cstr_x_fields_format_as_str(F)                                         \
    F(format_as_str, char const *, buf)                                        \
    F(simple, size_t, len)

// prexy struct messages
// {
//     struct cstr buf[5];
// };
#define messages_x_fields(F) F(struct_array, cstr, buf, 5)

#endif
